[tool.poetry]
name = "pdf-tools"
version = "0.1.0"
description = ""
authors = ["Henry Till <henrytill@gmail.com>"]
readme = "README.md"
packages = [{ include = "pdf_tools" }]

[tool.poetry.dependencies]
python = "^3.11"
pikepdf = "^7.1.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "pdf_tools:main"

[tool.black]
line-length = 88
